import DefaultLayout from "@/components/layout/DefaultLayout";
import "./globals.css";
import { Inter, Lora } from "next/font/google";

const inter = Inter({
    subsets: ["latin"],
    display: "swap",
    variable: "--font-inter",
});

const lora = Lora({
    subsets: ["latin"],
    display: "swap",
    variable: "--font-lora",
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${lora.variable} ${inter.variable}`}>
                <DefaultLayout>{children}</DefaultLayout>
            </body>
        </html>
    );
}
